name:                monitoring-server
version:             0.1.0.0
github:              githubuser/monitoring-server
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/monitoring-server#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.8.0
- aeson 
- binary
- ekg
- fast-logger
- http-types
- katip
- microlens 
- monad-logger
- monad-metrics > 0.2.0
- mtl
- persistent 
- persistent-template
- persistent-mysql-haskell
- safe
- servant 
- servant-server
- text
- wai
- wai-cors 
- wai-extra
- wai-middleware-metrics
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

default-extensions: 
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeFamilies
- DataKinds
- GeneralizedNewtypeDeriving

library:
  source-dirs: src

executables:
  monitoring-server-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - monitoring-server
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  monitoring-server-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - monitoring-server
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
